// This script is auto-generated by UINodeEditor, which is a tool given by PurpleFlowerCore
// Please do not modify this script manually
// url: https://github.com/Pditine/PurpleFlowerCore

using UnityEngine;
using UnityEngine.UI;
namespace UI
{
    public partial class UITarget
    {
        [SerializeField] private Image TargetImage;
        protected override void InitEvent()
        {

        }
    }
}