// This script is auto-generated by E2E
// Do not modify this script manually
// url: https://github.com/Pditine/E2E
using System;
using PurpleFlowerCore.Config;

namespace PurpleFlowerCore
{
    public class WeaponData1 : JsonConfig< WeaponData1Item>
    {
        protected override string GetLoadPath()
        {
            return "Assets/Data/Json/WeaponData1.json";
        }

        /// <summary>
        /// ID: 1001, 这是一把斧头
        /// </summary>
        public WeaponData1Item AXE => GetItem("1001"); 

        /// <summary>
        /// ID: 1002, 这是一把枪
        /// </summary>
        public WeaponData1Item M416 => GetItem("1002"); 

        /// <summary>
        /// ID: 1003, 这是一柄长矛
        /// </summary>
        public WeaponData1Item spear => GetItem("1003"); 
    }

    public abstract partial class PFCConfig
    {
        public static WeaponData1 WeaponData1 = new WeaponData1();
    }

    [Serializable]
    public class WeaponData1Item
    {
        public string Name; // 名称
        public int ATK; // 攻击力
        public float Dictance; // 攻击距离
        public float CD; // CD
    }
}
