// This script is auto-generated by UINodeEditor, which is a tool given by PurpleFlowerCore
// Please do not modify this script manually
// url: https://github.com/Pditine/PurpleFlowerCore

using UnityEngine;
using UnityEngine.UI;
namespace PurpleTest
{
    public partial class TestUI
    {
        [SerializeField] private Text MegText;
        [SerializeField] private Image BtnImage;
        [SerializeField] private Button BtnButton;
        protected override void InitEvent()
        {
            BtnButton.onClick.AddListener(BtnButtonClick);

        }
    }
}